name:
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - bzip2
  - ca-certificates
  - icu
  - ld_impl_linux-64
  - libexpat
  - libffi
  - libgcc
  - libgcc-ng
  - libgomp
  - liblzma
  - libnsl
  - libsqlite
  - libstdcxx
  - libuuid
  - libxcrypt
  - libzlib
  - ncurses
  - openssl
  - packaging
  - pip
  - python=3.10
  - readline
  - setuptools
  - tk
  - tzdata
  - wheel
  - zstd
  - pip:
      - absl-py
      - cloudpickle
      - contourpy
      - cycler
      - etils
      - farama-notifications
      - filelock
      - fonttools
      - fsspec
      - glfw
      - gymnasium
      - gymnasium-robotics
      - imageio
      - importlib-resources
      - jinja2
      - kiwisolver
      - markupsafe
      - matplotlib
      - mpmath
      - mujoco
      - networkx
      - numpy
      - pettingzoo
      - pillow
      - pyopengl
      - pyparsing
      - python-dateutil
      - six
      - sympy
      - torch
      - torchvision
      - tqdm
      - typing-extensions
      - zipp
prefix:
